#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

GPU_IDS="${GPU_IDS:-0,1,2,3}" \
MAX_MODEL_LEN="${MAX_MODEL_LEN:-2048}" \
MAX_NUM_BATCHED_TOKENS="${MAX_NUM_BATCHED_TOKENS:-2048}" \
GPU_MEMORY_UTILIZATION="${GPU_MEMORY_UTILIZATION:-0.82}" \
ENABLE_EXPERT_PARALLEL="${ENABLE_EXPERT_PARALLEL:-0}" \
ENFORCE_EAGER="${ENFORCE_EAGER:-1}" \
"${SCRIPT_DIR}/start_qwen3_vl_235b_h20_4gpu.sh"
